version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bikeride
    volumes:
      - blog_postgres:/var/lib/postgresql/data
    ports:
      - 1234:5432

volumes:
  blog_postgres:
