version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bikeride
    volumes:
      - blog_postgres:/var/lib/postgresql/data
    ports:
      - 1234:5432

  nginx:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8080:80

volumes:
  blog_postgres:
