FROM node:15-alpine
WORKDIR /usr/src/app
# Only copy the package.json file to work directory
COPY package.json .
# Install all Packages
RUN npm install
# Copy all other source code to work directory
ADD . /usr/src/app
# TypeScript
RUN npm run build-be
# Start
CMD [ "node", "build/backend/server.js" ]
EXPOSE 5000
