version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bikeride
    volumes:
      - blog_postgres:/var/lib/postgresql/data
    ports:
      - 1234:5432

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./develop/proxy/nginx.conf:/etc/nginx/conf:ro
      - ./develop/proxy/conf.d:/etc/nginx/conf.d:ro
    network_mode: "host"


volumes:
  blog_postgres:
