apiVersion: v1
kind: Service
metadata:
  name: be-service 
  labels:
    app: be
spec:
  ports:
  - port: 5000
  selector:
    app: be
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be
        image: lennartvanlaake/bikeride-be:latest 
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: node-env 
      imagePullSecrets:
        - name: regcred
