kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "ingress"

spec:
  rules:
    - host: lennartsbigbikeride.eu
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              serviceName: fe-service
              servicePort: 80
          - pathType: Prefix
            path: /api
            backend:
              serviceName: be-service
              servicePort: 5000
