apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: lennartvanlaake/bikeride-migrate:latest 
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: node-env 
        command: ["yarn",  "migrate"]
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
