apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service 
  labels:
    app: pg
spec:
  ports:
  - port: 5432
  selector:
    app: pg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec: 
      containers:
        - name: postgres
          image: postgres:latest
          ports:
              - containerPort: 5432
          envFrom:
              - configMapRef:
                  name: config
              - secretRef:
                  name: postgres
          volumeMounts:
              - mountPath: /var/lib/postgresql/data
                name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
