import type { Blog } from "../../../types/types";
export declare const baseUrl: string;
export declare const createBlog: (req: any) => Promise<string>;
export declare const updateBlog: (req: any, id: string) => Promise<import("axios").AxiosResponse<any>>;
export declare const getAllBlogs: () => Promise<Blog[]>;
export declare const getBlog: (id: string) => Promise<Blog>;
export declare const deleteBlog: (id: string) => Promise<import("axios").AxiosResponse<any>>;
export declare const linkImageToBlog: (imageId: string, blogId: string) => Promise<import("axios").AxiosResponse<any>>;
export declare const changeImageDescription: (imageId: string, req: any) => Promise<import("axios").AxiosResponse<any>>;
export declare const login: (req: any) => Promise<import("axios").AxiosResponse<any>>;
export declare const isLoggedIn: () => Promise<Boolean>;
